=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/schemas/service.schema.json
{
  "$id": "https://schema.kainos.com/service.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Service",
  "description": "A service describing the entire form.",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of your service, included in the header.",
      "type": "string"
    },
    "designSystem": {
      "description": "Defining renderer. Values: gds, gcds, ouds, wds, nhsds and fcads. Default: gds",
      "type": "string",
      "oneOf": [
        { "type": "string", "const": "gds" },
        { "type": "string", "const": "gcds" },
        { "type": "string", "const": "ouds" },
        { "type": "string", "const": "wds" },
        { "type": "string", "const": "nhsds" },
        { "type": "string", "const": "fcads" }
      ]
    },
    "productName": {
      "description": "Product name, used when the product name follows on directly from the design system logo. For example, GOV.UK Pay or GOV.UK Design System.",
      "type": "string"
    },
    "homePageUrl": {
      "description": "The URL of the homepage. Default: '#'",
      "type": "string"
    },
    "firstPage": {
      "description": "URL for the service name anchor.",
      "type": "string",
      "pattern": "^[a-zA-Z- ]*$"
    },
    "cookieSecret": {
      "description": "Value used to encrypt (AES) data in cookie.",
      "type": "string"
    },
    "cookieBanner": {
      "description": "Definition of cookie banner. If not set banner is not rendered.",
      "type": ["object", "null"]
    },
    "footer": {
      "description": "Footer used at the bottom of every page of your service",
      "type": ["object", "null"],
      "properties": {
        "links": {
          "description": "List of links that will be added to footer meta section.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "text": {
                "description": "Link text",
                "type": "string"
              },
              "href": {
                "description": "Link url",
                "type": "string"
              },
              "attributes": {
                "description": "HTML attributes added to the link",
                "type": "object"
              }
            }
          }
        }
      }
    },
    "pages": {
      "description": "The list of pages in the form.",
      "type": "array",
      "items": {
        "$ref": "https://schema.kainos.com/page.schema.json"
      },
      "minItems": 1
    },
    "apiMappings": {
      "description": "The list field mappings",
      "type": "object"
    },
    "apiServiceDefinition": {
      "$ref": "http://openapis.org/v3/schema.json#"
    },
    "authentication": {
      "$ref": "https://schema.kainos.com/authentication.schema.json"
    }
  },
  "required": ["name", "productName", "firstPage", "cookieSecret", "pages"]
}

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/character-counter-test-max-length-set/character-counter-test-max-length-set.json
{
    "name": "character counter test max length set",
    "firstPage": "firstPage",
    "productName": "example.com",
    "homePageUrl": "https://example.com",
    "cookieSecret": "0123456789-abc",
    "pages": [
      {
        "id": "firstPage",
        "nextPage": "",
        "preRequisiteData": null,
        "validation": null,
        "elements": [
          {
            "type": "Row2",
            "elements": [
              {
                "type": "Column",
                "columnWidth": "two-thirds",
                "elements": [
                  {
                    "type": "Form",
                    "classes": "",
                    "elements": [
                      {
                        "type": "ErrorList",
                        "title": "There is a problem"
                      },
                      {
                        "type": "TextAreaField",
                        "name": "f_textarea_1",
                        "displayText": "Description",
                        "hint": "Please enter a description",
                        "maxLength": 500
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/inset-text-test/inset-text-test.json
{
  "name": "Your Service Name",
  "firstPage": "firstPage",
  "productName": "Demo",
  "homePageUrl": "",
  "cookieSecret": "0123456789-abc",
  "pages": [
    {
      "id": "firstPage",
      "nextPage": null,
      "elements": [
        {
          "type": "InsetText",
          "displayText": "Testing InsetText. This is display text."
        }
      ]
    }
  ]
}

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/summary-date-test/summary-date-test.json
{
  "name": "Your Service Name",
  "firstPage": "firstPage",
  "productName": "Demo",
  "homePageUrl": "",
  "cookieSecret": "0123456789-abc",
  "pages": [
    {
      "id": "firstPage",
      "nextPage": "secondPage",
      "elements": [
        {
            "type": "Form",
            "elements": [
                {
                    "type": "ErrorList",
                    "title": "There is a problem"
                  },
                  {
                    "type": "DatePickerField",
                    "name": "f-dateInput",
                    "displayText": "Event Date",
                    "hint": "Please provide the date of the event.",
                    "validation": {
                        "regex": "^([0-9]|0[1-9]|[12][0-9]|3[01]) ([0-9]|0[1-9]|1[0-2]) (19|20)\\d{2}$",
                        "error": "Wrong format",
                        "isMandatory": true,
                        "mandatoryError": "Cannot be left empty"
                    }
                  },
                  {
                    "type": "SubmitButton",
                    "displayText": "Save and Continue"
                }
            ]
          }
        ]
      },
    {
      "id": "secondPage",
      "nextPage": "null",
      "elements": [
        {
            "type": "Form",
            "elements": [
              {
                    "type": "Summary",
                    "fieldNames": [
                      "f-dateInput"
                    ]
                }
            ]
          }
        ]
      }
    ]
  }

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/bulleted-list-test/bulleted-list-test.json
{
    "name": "Your Service Name",
    "firstPage": "firstPage",
    "productName": "Demo",
    "homePageUrl": "",
    "cookieSecret": "0123456789-abc",
    "pages": [
      {
        "id": "firstPage",
        "nextPage": null,
        "elements": [
          {
            "type": "BulletedListField",
            "name": "bulletedListField",
            "displayText": "Testing Bulleted list. This is display text.",
            "items": [
                {"text": "Item 1"},
                {"text": "Item 2"},
                {"text": "Item 3"}
            ]
          }
        ]
      }
    ]
  }

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/cookies-page-test/cookies-page-test.json
{
  "name": "cookie",
  "firstPage": "firstPage",
  "productName": "cookie",
  "homePageUrl": "",
  "cookieSecret": "0123456789-abc",
  "footer": {
    "links": [
      {
        "text": "example external link",
        "href": "https://google.com",
        "attributes": {
          "target": "_blank"
        }
      },
      {
        "text": "Cookies",
        "href": "cookie"
      }
    ]
  },
  "pages": [
    {
      "id": "cookie",
      "nextPage": null,
      "elements": [
        {
          "type": "Row2",
          "elements": [
            {
              "type": "Column",
              "columnWidth": "two-thirds",
              "elements": [
                {
                  "type": "Heading",
                  "displayText": "Cookies"
                },
                {
                  "type": "Paragraph",
                  "displayText": "Cookies are small files saved on your phone, table or computer when you visit a website."
                },
                {
                  "type": "Subheading",
                  "displayText": "Essential cookies"
                },
                {
                  "type": "Paragraph",
                  "displayText": "Essential cookies keep your information secure while you use this service. We do not need to ask your permission to use them."
                },
                {
                  "type": "CookiesTable",
                  "displayText": "",
                  "cookies": []
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/backbutton-test/backbutton-test.json
{
    "name": "backbutton test",
    "firstPage": "firstPage",
    "productName": "example.com",
    "homePageUrl": "https://example.com",
    "cookieSecret": "0123456789-abc",
    "pages": [
      {
        "id": "firstPage",
        "nextPage": "secondPage",
        "preRequisiteData": null,
        "validation": null,
        "elements": [
          {
            "type": "Row2",
            "elements": [
              {
                "type": "Column",
                "columnWidth": "two-thirds",
                "elements": [
                  {
                    "type": "Form",
                    "classes": "",
                    "elements": [
                      {
                        "type": "ErrorList",
                        "title": "There is a problem"
                      },
                      {
                        "type": "SubmitButton",
                        "displayText": "Submit"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "secondPage",
        "nextPage": "",
        "preRequisiteData": null,
        "validation": null,
        "elements": [
          {
            "type": "Row2",
            "elements": [
              {
                "type": "Column",
                "columnWidth": "two-thirds",
                "elements": [
                  {
                    "type": "Form",
                    "classes": "",
                    "elements": [
                      {
                        "type": "ErrorList",
                        "title": "There is a problem"
                      },
                      {
                        "type": "BackButton",
                        "displayText": "Back",
                        "classes": "govuk-button--secondary"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/email-address-test/email-address-test.json
{
    "name": "Email Address Input Demo",
    "firstPage": "firstPage",
    "productName": "Demo",
    "homePageUrl": "",
    "cookieSecret": "0123456789-abc",
    "footer": {},
    "pages": [
      {
        "id": "firstPage",
        "nextPage": "secondPage",
        "elements": [
          {
            "type": "Form",
            "elements": [
              {
                "type": "ErrorList",
                "title": "There is a problem"
              },
              {
                "type": "EmailField",
                "name": "email",
                "displayText": "What is your email address?",
                "labelClasses": "govuk-fieldset__legend--l",
                "isPageHeading": true,
                "validation": {
                  "isMandatory": true
                }
              },
              {
                "type": "SubmitButton",
                "displayText": "Save and Continue"
              }
            ]
          }
        ]
      },
      {
        "id": "secondPage",
        "nextPage": null,
        "elements": [
          {
            "type": "Summary",
            "title": "Summary title",
            "fieldNames": ["email"]
          }
        ]
      }
    ],
    "apiMappings": {},
    "apiServiceDefinition": {
      "openapi": "3.0.1",
      "info": {
        "title": "api",
        "version": "1.0.0"
      },
      "paths": {}
    }
  }

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/services/newsletter-demo.json
{
  "name": "Newsletter signup",
  "firstPage": "firstPage",
  "productName": "example.com",
  "homePageUrl": "https://example.com",
  "cookieSecret": "0123456789-abc",
  "footer": {},
  "pages": [
    {
      "id": "firstPage",
      "nextPage": "Completed",
      "preRequisiteData": null,
      "validation": null,
      "elements": [
        {
          "type": "Row2",
          "elements": [
            {
              "type": "Column",
              "columnWidth": "two-thirds",
              "elements": [
                {
                  "type": "ErrorList",
                  "title": "There is a problem"
                },
                {
                  "type": "Form",
                  "classes": "",
                  "elements": [
                    {
                      "type": "TextField",
                      "name": "name",
                      "displayText": "Your name",
                      "autocomplete": null,
                      "validation": null,
                      "classes": null,
                      "hint": ""
                    },
                    {
                      "type": "TextField",
                      "name": "email",
                      "displayText": "Email address",
                      "autocomplete": null,
                      "validation": null,
                      "classes": null,
                      "hint": ""
                    },
                    {
                      "type": "SubmitButton",
                      "displayText": "Submit",
                      "action": {
                        "value": "submit",
                        "operation": "submitForm",
                        "validation": true
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "id": "Completed",
      "nextPage": "",
      "preRequisiteData": null,
      "validation": null,
      "elements": [
        {
          "type": "Row2",
          "elements": [
            {
              "type": "Column",
              "columnWidth": "two-thirds",
              "elements": [
                {
                  "type": "Form",
                  "classes": "",
                  "elements": [
                    {
                      "type": "Panel",
                      "title": "Enquiry submitted",
                      "text": "Your reference number is <b>ABCD1234</b>"
                    },
                    {
                      "type": "Paragraph",
                      "displayText": "We have sent you a confirmation email."
                    },
                    {
                      "type": "SubHeading",
                      "displayText": "What happens next"
                    },
                    {
                      "type": "Paragraph",
                      "displayText": "We have sent your enquiry."
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "apiMappings": {
    "submitForm": {
      "request": {
        "name": "userName",
        "email": "userEmail"
      },
      "response": {
        "title": "message",
        "fieldNames": "data[*].fieldName",
        "fieldErrorMessages": "data[*].errorMessage",
        "numErrors": "length(data)"
      }
    }
  },
  "apiServiceDefinition": {
    "openapi": "3.0.1",
    "info": {
      "title": "form-submission-API",
      "version": "2024-06-13T12:12:41Z"
    },
    "servers": [
      {
        "url": "https://example-endpoint.com/{basePath}",
        "variables": {
          "basePath": {
            "default": "dev-playground"
          }
        }
      }
    ],
    "paths": {
      "/submit-form/service": {
        "post": {
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FormModel"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "200 response",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Empty"
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "Empty": {
          "title": "Empty Schema",
          "type": "object"
        },
        "FormModel": {
          "title": "FormModel",
          "type": "object",
          "properties": {
            "applicant": {
              "$ref": "#/components/schemas/FormModelApplicant"
            }
          }
        },
        "FormModelApplicant": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "address": {
              "type": "string"
            },
            "postcode": {
              "type": "string"
            },
            "phoneNumber": {
              "type": "number"
            },
            "emailAddress": {
              "type": "string"
            },
            "testLocation": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
