=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/schemas/service.schema.json
{
  "$id": "https://schema.kainos.com/service.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Service",
  "description": "A service describing the entire form.",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of your service, included in the header.",
      "type": "string"
    },
    "designSystem": {
      "description": "Defining renderer. Values: gds, gcds, ouds, wds, nhsds and fcads. Default: gds",
      "type": "string",
      "oneOf": [
        { "type": "string", "const": "gds" },
        { "type": "string", "const": "gcds" },
        { "type": "string", "const": "ouds" },
        { "type": "string", "const": "wds" },
        { "type": "string", "const": "nhsds" },
        { "type": "string", "const": "fcads" }
      ]
    },
    "productName": {
      "description": "Product name, used when the product name follows on directly from the design system logo. For example, GOV.UK Pay or GOV.UK Design System.",
      "type": "string"
    },
    "homePageUrl": {
      "description": "The URL of the homepage. Default: '#'",
      "type": "string"
    },
    "firstPage": {
      "description": "URL for the service name anchor.",
      "type": "string",
      "pattern": "^[a-zA-Z- ]*$"
    },
    "cookieSecret": {
      "description": "Value used to encrypt (AES) data in cookie.",
      "type": "string"
    },
    "cookieBanner": {
      "description": "Definition of cookie banner. If not set banner is not rendered.",
      "type": ["object", "null"]
    },
    "footer": {
      "description": "Footer used at the bottom of every page of your service",
      "type": ["object", "null"],
      "properties": {
        "links": {
          "description": "List of links that will be added to footer meta section.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "text": {
                "description": "Link text",
                "type": "string"
              },
              "href": {
                "description": "Link url",
                "type": "string"
              },
              "attributes": {
                "description": "HTML attributes added to the link",
                "type": "object"
              }
            }
          }
        }
      }
    },
    "pages": {
      "description": "The list of pages in the form.",
      "type": "array",
      "items": {
        "$ref": "https://schema.kainos.com/page.schema.json"
      },
      "minItems": 1
    },
    "apiMappings": {
      "description": "The list field mappings",
      "type": "object"
    },
    "apiServiceDefinition": {
      "$ref": "http://openapis.org/v3/schema.json#"
    },
    "authentication": {
      "$ref": "https://schema.kainos.com/authentication.schema.json"
    }
  },
  "required": ["name", "productName", "firstPage", "cookieSecret", "pages"]
}

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/conditional-logic-next-page-test/conditional-logic-next-page-test.json
{
  "name": "Your Service Name",
  "firstPage": "radio field",
  "productName": "Demo",
  "homePageUrl": "",
  "cookieSecret": "0123456789-abc",
  "cookieBanner": null,
  "footer": null,
  "pages": [
    {
      "id": "radio field",
      "nextPage": {
        "rules": [
          {
            "match": {
              "f-radio-2": "Second"
            },
            "page": "secondPage"
          },
          {
            "match": {
              "f-radio-2": "Third"
            },
            "page": "thirdPage"
          }
        ]
      },
      "elements": [
        {
          "type": "Form",
          "elements": [
            {
              "type": "RadioField",
              "name": "f-radio-2",
              "validation": {
                "isMandatory": true
              },
              "options": [
                {
                  "value": "Second",
                  "text": "Second",
                  "valueText": "Second"
                },
                {
                  "value": "Third",
                  "text": "Third",
                  "valueText": "Third"
                }
              ],
              "displayText": "Choose one:",
              "labelClasses": "govuk-fieldset__legend--l",
              "isPageHeading": true,
              "hint": "Select one option"
            },
            {
              "type": "SubmitButton",
              "displayText": "Save and continue"
            }
          ]
        }
      ]
    },
    {
      "id": "seconPage",
      "nextPage": "thirdPage",
      "elements": [
        {
          "type": "Form",
          "elements": [
            {
              "type": "Heading",
              "displayText": "This is the second page of the service"
            }
          ]
        }
      ]
    },
    {
      "id": "thirdPage",
      "nextPage": null,
      "elements": [
        {
          "type": "Form",
          "elements": [
            {
              "type": "Heading",
              "displayText": "This is the third page of the service"
            }
          ]
        }
      ]
    }
  ],
  "apiMappings": {},
  "apiServiceDefinition": {
    "openapi": "3.0.1",
    "info": {
      "title": "api",
      "version": "1.0.0"
    },
    "paths": {}
  }
}

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/upload-file-automatic-test/upload-file-automatic-test.json
{
  "name": "root.header.service-name",
  "firstPage": "Upload Your Passport Photo",
  "productName": "example.com",
  "homePageUrl": "https://example.com",
  "cookieSecret": "0123456789-abc",
  "cookieBanner": null,
  "footer": {},
  "pages": [
    {
      "id": "Upload Your Passport Photo",
      "nextPage": "Submitted",
      "elements": [
        {
          "type": "Phase",
          "name": "Alpha",
          "displayText": "This is a new service"
        },
        {
          "type": "BackButton",
          "displayText": "Back"
        },
        {
          "type": "Row2",
          "elements": [
            {
              "type": "Column",
              "elements": [
                {
                  "type": "ErrorList",
                  "title": "There is a problem"
                },
                {
                  "type": "Form",
                  "elements": [
                    {
                      "type": "FileUpload",
                      "name": "f-file-upload",
                      "displayText": "Please upload your passport photo",
                      "hint": "Ensure your photo is a clear",
                      "labelClasses": "govuk-label--l",
                      "isPageHeading": true,
                      "validation": {
                        "isMandatory": true
                      },
                      "maxFileSize": 5,
                      "allowedFileTypes": [
                        "application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        "image/jpeg",
                        "application/pdf",
                        "image/png",
                        "application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                      ]
                    },
                    {
                      "type": "SubmitButton",
                      "displayText": "Save and continue"
                    }
                  ]
                }
              ],
              "columnWidth": "two-thirds"
            }
          ]
        }
      ]
    },
    {
      "id": "Submitted",
      "nextPage": "Feedback Page",
      "elements": [
        {
          "type": "Row2",
          "elements": [
            {
              "type": "Column",
              "elements": [
                {
                  "type": "Panel",
                  "title": "Enquiry saved",
                  "text": "Your reference number"
                },
                {
                  "type": "Heading",
                  "displayText": "What happens next",
                  "size": "h3"
                },
                {
                  "type": "Paragraph",
                  "displayText": "Your enquiry has been submitted"
                },
                {
                  "type": "Paragraph",
                  "displayText": "Leave feedback to help us improve this service"
                }
              ],
              "columnWidth": "two-thirds"
            }
          ]
        }
      ]
    }
  ],
  "apiMappings": {
    "submitForm": {
      "request": {
        "_SESSION-ID_": "_SESSION-ID_",
        "f-file-upload": "f-file-upload"
      },
      "response": {
        "title": "message",
        "fieldNames": "data[*].fieldName",
        "fieldErrorMessages": "data[*].errorMessage",
        "numErrors": "length(data)",
        "referenceNumber": "referenceNumber"
      }
    },
    "sendFeedback": {
      "request": {
        "_SESSION-ID_": "_SESSION-ID_",
        "feel-about-service": "feel-about-service",
        "easy-to-use": "easy-to-use",
        "meet-your-needs": "meet-your-needs",
        "additional-feedback": "additional-feedback"
      },
      "response": {
        "title": "message",
        "fieldNames": "data[*].fieldName",
        "fieldErrorMessages": "data[*].errorMessage",
        "numErrors": "length(data)",
        "referenceNumber": "referenceNumber"
      }
    }
  },
  "apiServiceDefinition": {
    "openapi": "3.0.1",
    "info": {
      "title": "api",
      "version": "1.0.0"
    },
    "paths": {
      "/dev/submit-form/service": {
        "servers": [
          {
            "url": "https://example.com"
          }
        ],
        "post": {
          "operationId": "submitForm",
          "responses": {
            "200": {
              "description": "successful operation"
            }
          }
        }
      }
    }
  }
}

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/page-not-found-test/page-not-found-test.json
{
    "name": "Your Service Name",
    "firstPage": "first",
    "productName": "Demo",
    "homePageUrl": "",
    "cookieSecret": "0123456789-abc",
    "footer": null,
    "pages": [
        {
            "id": "not-found",
            "nextPage": null,
            "elements": [
              {
                "type": "Row2",
                "elements": [
                  {
                    "type": "Column",
                    "columnWidth": "two-thirds",
                    "elements": [
                      {
                        "type": "Paragraph",
                        "displayText": "My custom not found page for testing purposes"
                      }
                    ]
                  }
                ]
              }
            ]
          }
    ]
}

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/cookie-banner-test/cookie-banner-test.json
{
    "name": "Your Service Name",
    "firstPage": "firstPage",
    "productName": "Demo",
    "homePageUrl": "",
    "cookieBanner": null,
    "cookieSecret": "0123456789-abc",
    "footer": {
    "links": [
      {
        "text": "example external link",
        "href": "https://google.com",
        "attributes": {
          "target": "_blank"
        }
      }
    ]
  },
    "pages": [
      {
        "id": "firstPage",
        "nextPage": "secondPage",
        "elements": [
          {
              "type": "Form",
              "elements": [
                  {
                      "type": "ErrorList",
                      "title": "There is a problem"
                    },
                    {
                      "type": "DatePickerField",
                      "name": "f-dateInput",
                      "displayText": "Event Date",
                      "hint": "Please provide the date of the event.",
                      "validation": {
                          "regex": "^([0-9]|0[1-9]|[12][0-9]|3[01]) ([0-9]|0[1-9]|1[0-2]) (19|20)\\d{2}$",
                          "error": "Wrong format",
                          "isMandatory": true,
                          "mandatoryError": "Cannot be left empty"
                      }
                    },
                    {
                      "type": "SubmitButton",
                      "displayText": "Save and Continue"
                  }
              ]
            }
          ]
        },
      {
        "id": "cookie",
      "nextPage": null,
      "elements": [
        {
          "type": "Row2",
          "elements": [
            {
              "type": "Column",
              "columnWidth": "two-thirds",
              "elements": [
                {
                  "type": "Heading",
                  "displayText": "Cookies"
                },
                {
                  "type": "Paragraph",
                  "displayText": "Cookies are small files saved on your phone, table or computer when you visit a website."
                },
                {
                  "type": "Subheading",
                  "displayText": "Essential cookies"
                },
                {
                  "type": "Paragraph",
                  "displayText": "Essential cookies keep your information secure while you use this service. We do not need to ask your permission to use them."
                },
                {
                  "type": "CookiesTable",
                  "displayText": "",
                  "cookies": []
                }
              ]
            }
          ]
        }
      ]
    }
    ]
}

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/postcode-field-automatic-test/postcode-field-automatic-test.json
{
    "name": "Postcode Input Demo",
    "firstPage": "firstPage",
    "productName": "Demo",
    "homePageUrl": "",
    "cookieSecret": "0123456789-abc",
    "footer": {},
    "pages": [
      {
        "id": "firstPage",
        "nextPage": "secondPage",
        "elements": [
          {
            "type": "Form",
            "elements": [
              {
                "type": "ErrorList",
                "title": "There is a problem"
              },
              {
                "type": "PostcodeField",
                "name": "f-postcodeInput",
                "displayText": "What is your postcode?",
                "labelClasses": "govuk-fieldset__legend--l",
                "isPageHeading": true
              },
              {
                "type": "SubmitButton",
                "displayText": "Save and Continue"
              }
            ]
          }
        ]
      },
      {
        "id": "secondPage",
        "nextPage": null,
        "elements": [
            {
              "type": "Summary",
              "title": "Summary title",
              "fieldNames": [
                "f-postcodeInput"
              ]
            }
          ]
        }
      ],
    "apiMappings": {},
    "apiServiceDefinition": {
      "openapi": "3.0.1",
      "info": {
        "title": "api",
        "version": "1.0.0"
      },
      "paths": {}
    }
  }

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/date-input-automatic-test/date-input-automatic-test.json
{
    "name": "Your Service Name",
    "firstPage": "firstPage",
    "productName": "Demo",
    "homePageUrl": "",
    "cookieSecret": "0123456789-abc",
    "footer": {
  
    },
    "pages": [
      {
        "id": "firstPage",
        "nextPage": "secondPage",
        "elements": [
          {
            "type": "Form",
            "elements": [
              {
                "type": "ErrorList",
                "title": "There is a problem"
              },
              {
                "type": "DatePickerField",
                "name": "f-dateInput-2",
                "validation": {
                  "isMandatory": true,
                  "mandatoryError": "Cannot be left empty"
                },
                "displayText": "Event date",
                "labelClasses": "govuk-fieldset__legend--l",
                "isPageHeading": true,
                "hint": "For example, 27 3 2007"
              },
              {
                "type": "SubmitButton",
                "displayText": "Save and Continue"
              }
            ]
          }
        ]
      },
      {
        "id": "secondPage",
        "nextPage": "thirdPage",
        "elements": [
          {
            "type": "Form",
            "elements": [
              {
                "type": "ErrorList",
                "title": "There is a problem"
              },
              {
                "type": "DatePickerField",
                "name": "f-dateInput-3",
                "validation": {
                  "isMandatory": false,
                  "mandatoryError": "Cannot be left empty"
                },
                "displayText": "Event date",
                "labelClasses": "govuk-fieldset__legend--l",
                "isPageHeading": true,
                "hint": "For example, 27 3 2007"
              },
              {
                "type": "SubmitButton",
                "displayText": "Save and Continue"
              }
            ]
          }
        ]
      },
      {
        "id": "thirdPage",
        "nextPage": null,
        "elements": [
          {
            "type": "Form",
            "elements": []
          }
        ]
      }
    ],
    "apiMappings": {
  
    },
    "apiServiceDefinition": {
      "openapi": "3.0.1",
      "info": {
        "title": "api",
        "version": "1.0.0"
      },
      "paths": {
  
      }
    }
  }

=== KainosSoftwareLtd/KainosStudio-CoreApp-Public/CoreDeployable/test/kfd-test-files/back-link-conditional-test/back-link-conditional-test.json
{
    "name": "Your Service Name",
    "firstPage": "radioField",
    "productName": "Demo",
    "homePageUrl": "",
    "cookieSecret": "0123456789-abc",
    "cookieBanner": null,
    "footer": null,
    "pages": [
      {
        "id": "radioField",
        "nextPage": {
          "rules": [
            {
              "match": {
                "f-radio-2": "Second"
              },
              "page": "secondPage"
            },
            {
              "match": {
                "f-radio-2": "Third"
              },
              "page": "thirdPage"
            },
            {
                "match": {
                  "f-radio-2": "Fourth"
                },
                "page": "fourthPage"
              },
              {
                "match": {
                  "f-radio-2": "Fifth"
                },
                "page": "fifthPage"
              }
          ]
        },
        "elements": [
          {
            "type": "Form",
            "elements": [
              {
                "type": "RadioField",
                "name": "f-radio-2",
                "validation": {
                  "isMandatory": true
                },
                "options": [
                  {
                    "value": "Second",
                    "text": "Second",
                    "valueText": "Second"
                  },
                  {
                    "value": "Third",
                    "text": "Third",
                    "valueText": "Third"
                  },
                  {
                    "value": "Fourth",
                    "text": "Fourth",
                    "valueText": "Fourth"
                  },
                  {
                    "value": "Fifth",
                    "text": "Fifth",
                    "valueText": "Fifth"
                  }
                ],
                "displayText": "Choose one:",
                "labelClasses": "govuk-fieldset__legend--l",
                "isPageHeading": true,
                "hint": "Select one option"
              },
              {
                "type": "SubmitButton",
                "displayText": "Save and continue"
              }
            ]
          }
        ]
      },
      {
        "id": "secondPage",
        "nextPage": "thirdPage",
        "elements": [
            {
                "type": "BackButton"
            },
          {
            "type": "Form",
            "elements": [
              {
                "type": "Heading",
                "displayText": "This is the second page of the service"
              }
            ]
          }
        ]
      },
      {
        "id": "thirdPage",
        "nextPage": null,
        "elements": [
            {
                "type": "BackButton"
            },
          {
            "type": "Form",
            "elements": [
              {
                "type": "Heading",
                "displayText": "This is the third page of the service"
              }
            ]
          }
        ]
      },
      {
        "id": "fourthPage",
        "nextPage": null,
        "elements": [
            {
                "type": "BackButton"
            },
          {
            "type": "Form",
            "elements": [
              {
                "type": "Heading",
                "displayText": "This is the fourth page of the service"
              }
            ]
          }
        ]
      },
      {
        "id": "fifthPage",
        "nextPage": null,
        "elements": [
            {
                "type": "BackButton"
            },
          {
            "type": "Form",
            "elements": [
              {
                "type": "Heading",
                "displayText": "This is the fifth page of the service"
              }
            ]
          }
        ]
      }
    ],
    "apiMappings": {},
    "apiServiceDefinition": {
      "openapi": "3.0.1",
      "info": {
        "title": "api",
        "version": "1.0.0"
      },
      "paths": {}
    }
  }
